# Generated by Django 4.0 on 2024-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_date_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amaunt_paid',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
